### ISSUE TITLE
What is the expected number of sets?

### ISSUE THREAD

**Issue by travisdowns** [IAIK/drama#4]
What should the expected number of sets be? The total number of sets of non-conflicting (at the row level) addresses?

For example, on a dual channel system, with 2 ranks/DIMM and DDR4 (16 banks), does that lead to 2 * 2 * 16 = 64 sets? Based on the default value of 8, I'm guessing that's not correct...

**Comment by dgruss** [comment]
64, yes. The number of sets you specify is a minimum + you only need half of the sets to know all of them.Am 24.11.2018 23:55 schrieb travisdowns <notifications@github.com>:What should the expected number of sets be? The total number of sets of non-conflicting (at the row level) addresses?
For example, on a dual channel system, with 2 ranks/DIMM and DDR4 (16 banks), does that lead to 2 * 2 * 16 = 64 sets? Seems like too many if you have the default value at 8...
